(function () {
  "use strict";
  var REPO = "https://github.com/m9wmtcb782-arch/AIVAULT";
  var CONN_KEY = "aivault.collab.v011.conn";
  var TYPES = ["MESSAGE","CODE","REVIEW","FIX","TEST","PASS","FAIL","WARNING","DECISION","GATE","OWNER"];
  var GATES = [["contract","Contract"],["coordinator","Coordinator"],["router","Router"],["reserve","Reserve"],["execution","Execution"],["verification","Verification"],["settlement","Settlement"],["gate1","Gate 1"],["gate2","Gate 2"],["gate3","Gate 3"],["production","Production"]];
  var SEED_AGENTS = [
    {agent_id:"chatgpt",display_name:"ChatGPT",role:"architect",capability:"architecture / review / gate",color:"#5ec8ff"},
    {agent_id:"grok",display_name:"Grok",role:"builder",capability:"implementation / coding",color:"#e0b14a"},
    {agent_id:"gemini",display_name:"Gemini",role:"researcher",capability:"research / analysis",color:"#8b7dff"},
    {agent_id:"darkstar",display_name:"Technical Dark Star",role:"engineer",capability:"engineering / testing / learning",color:"#3dcc8a"},
    {agent_id:"auditor",display_name:"Auditor",role:"auditor",capability:"security / compliance / risk",color:"#e85d5d"}
  ];
  var ALIAS = {architect:"chatgpt",builder:"grok",researcher:"gemini",darkstar:"darkstar",engineer:"darkstar",auditor:"auditor"};
  var OWNER_ACTIONS = {start:1,pause:1,rereview:1,approve_change:1,reject:1,approve_gate:1,approve_prod:1};
  var db = emptyCache();
  var conn = null;
  var connState = "not_connected";
  function $(id){return document.getElementById(id);}
  function uid(prefix){return prefix+"-"+crypto.randomUUID();}
  function now(){return new Date().toISOString();}
  function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,function(c){return {"&":"&","<":"<",">":">","\"":""","'":"&#39;"}[c];});}
  function sl(s){var map={working:"Working",review:"Reviewing",reviewing:"Reviewing",researching:"Researching",testing:"Testing",blocked:"Blocked",paused:"Paused",waiting:"Waiting",connected:"CONNECTED",not_connected:"NOT CONNECTED"};return map[s]||s||"";}
  function gd(st){if(st==="pass")return '<span class="ok">PASS</span>';if(st==="waiting")return '<span class="wait">WAITING</span>';if(st==="fail")return '<span class="fail">FAIL</span>';if(st==="blocked")return '<span class="fail">BLOCKED</span>';return '<span class="idle">NOT STARTED</span>';}
  function setNote(msg){var el=$("connNote");if(el)el.textContent=msg;}
  function setBadge(){var el=$("badgeConn");if(!el)return;if(connState==="connected"){el.className="badge";el.textContent="CONNECTED";}else if(connState==="waiting"){el.className="badge warn";el.textContent="WAITING";}else{el.className="badge warn";el.textContent="NOT CONNECTED";}}
  function emptyCache(){return {agents:SEED_AGENTS.map(function(a){return Object.assign({},a,{status:"waiting",connection_status:"not_connected",current_task_id:null,current_action:"",last_activity_at:null});}),tasks:[],members:[],messages:[],reviews:[],actions:[],code_refs:[],tests:[],decisions:[],learning:[],gates:{},selected:"task-001",paused:false};}
  function detectSessionConn(){try{var i,key,raw,parsed,token,payload,ref,url;for(i=0;i<localStorage.length;i+=1){key=localStorage.key(i);if(!key||key.indexOf("sb-")!==0||key.indexOf("-auth-token")<0)continue;raw=localStorage.getItem(key);if(!raw)continue;parsed=JSON.parse(raw);token=parsed&&(parsed.access_token||(parsed.currentSession&&parsed.currentSession.access_token));if(!token||token.split(".").length<2)continue;payload=JSON.parse(atob(token.split(".")[1].replace(/-/g,"+").replace(/_/g,"/"));if(!payload||payload.role!=="authenticated")continue;ref=payload.ref;url=ref?("https://"+ref+".supabase.co"):null;if(!url)continue;return {url:url,key:token,token:token,source:"session"};}}catch(err){return null;}return null;}
  function loadSavedConn(){try{var raw=sessionStorage.getItem(CONN_KEY);if(!raw)return null;var c=JSON.parse(raw);if(!c||!c.url||!c.key)return null;if(/service_role/i.test(c.key))return null;return {url:c.url.replace(/\/$/,""),key:c.key,token:c.key,source:"form"};}catch(err){return null;}}
  async function rest(method,table,opts){opts=opts||{};if(!conn)throw new Error("NOT CONNECTED");var url=conn.url+"/rest/v1/"+table+(opts.query||"");var res=await fetch(url,{method:method,headers:{apikey:conn.key,Authorization:"Bearer "+conn.token,"Content-Type":"application/json",Prefer:opts.prefer||"return=representation"},body:opts.body?JSON.stringify(opts.body):undefined});var text=await res.text();var data=null;if(text){try{data=JSON.parse(text);}catch(err){data={raw:text};}}if(!res.ok){var msg=(data&&(data.message||data.error_description||data.error))||text||res.status;throw new Error(String(msg));}return data;}
  async function requireConn(){if(!conn){alert("NOT CONNECTED. Apply 005_agent_collaboration.sql on TEST project first.");throw new Error("NOT CONNECTED");}}
  function membersOf(taskId){return db.members.filter(function(m){return m.task_id===taskId;}).map(function(m){return m.agent_id;});}
  async function refreshAll(){var agents=await rest("GET","agent_registry",{query:"?select=*&order=created_at.asc"});var tasks=await rest("GET","agent_tasks",{query:"?select=*&order=created_at.asc"});var members=await rest("GET","agent_task_members",{query:"?select=*"});var messages=await rest("GET","agent_messages",{query:"?select=*&order=created_at.asc"});var reviews=await rest("GET","agent_reviews",{query:"?select=*&order=created_at.asc"});var actions=await rest("GET","agent_actions",{query:"?select=*&order=created_at.asc"});var codeRefs=await rest("GET","agent_code_refs",{query:"?select=*&order=created_at.asc"});var tests=await rest("GET","agent_test_results",{query:"?select=*&order=created_at.asc"});var decisions=await rest("GET","agent_decisions",{query:"?select=*&order=created_at.asc"});var learning=await rest("GET","agent_learning_candidates",{query:"?select=*&order=created_at.asc"});var gates=await rest("GET","agent_task_gates",{query:"?select=*"});var gateMap={};(gates||[]).forEach(function(g){if(!gateMap[g.task_id])gateMap[g.task_id]={};gateMap[g.task_id][g.gate_key]={state:g.state,note:g.note||""};});db.agents=agents||[];db.tasks=tasks||[];db.members=members||[];db.messages=messages||[];db.reviews=reviews||[];db.actions=actions||[];db.code_refs=codeRefs||[];db.tests=tests||[];db.decisions=decisions||[];db.learning=learning||[];db.gates=gateMap;if(!db.selected||!db.tasks.some(function(t){return t.task_id===db.selected;}))db.selected=db.tasks[0]?db.tasks[0].task_id:null;}
  async function connectAndLoad(){connState="waiting";setBadge();setNote("WAITING - probing agent_registry");try{await rest("GET","agent_registry",{query:"?select=agent_id&limit=1"});await refreshAll();connState="connected";setBadge();setNote("CONNECTED - registry is source of truth. No auto agent calls.");render();}catch(err){conn=null;connState="not_connected";setBadge();setNote("NOT CONNECTED - "+err.message);render();}}
  function ag(id){return db.agents.find(function(a){return a.agent_id===id;});}
  function cur(){return db.tasks.find(function(t){return t.task_id===db.selected;});}
  function resolve(token){var t=String(token||"").replace(/^@/,"").toLowerCase();if(ALIAS[t])return ALIAS[t];var a=db.agents.find(function(x){return x.agent_id.toLowerCase()===t||String(x.display_name).toLowerCase().replace(/\s+/g,"")===t||String(x.role).toLowerCase()===t;});return a?a.agent_id:null;}
  function mentions(text){var out=[],re=/@([A-Za-z][A-Za-z0-9_-]*)/g,m;while((m=re.exec(text))){var id=resolve(m[1]);if(id&&out.indexOf(id)<0)out.push(id);}return out;}
  function hi(text){return esc(text).replace(/@([A-Za-z][A-Za-z0-9_-]*)/g,'<span class="mention">@$1</span>');}
  function refHTML(r){var REPOU="https://github.com/m9wmtcb782-arch/AIVAULT";var f=REPOU+"/blob/"+(r.commit_sha||"main")+"/"+r.file_path;var c=r.commit_sha?REPOU+"/commit/"+r.commit_sha:"";return '<div class="links"><a href="'+f+'" target="_blank" rel="noopener">Code</a>'+(c?' <a href="'+c+'" target="_blank" rel="noopener">Diff</a>':'')+' <button type="button" class="btn" data-ask-review="'+esc(r.ref_id)+'">Review</button><div class="muted">'+esc(r.file_path)+(r.commit_sha?" · "+String(r.commit_sha).slice(0,7):"")+"</div></div>";}
  function fill(){if(!$("msgType"))return;var ct=$("msgType").value,cf=$("filterType").value;$("msgType").innerHTML=TYPES.map(function(t){return "<option>"+t+"</option>";}).join("");$("filterType").innerHTML='<option value="">ALL</option>'+TYPES.map(function(t){return '<option value="'+t+'">'+t+"</option>";}).join("");if(TYPES.indexOf(ct)>=0)$("msgType").value=ct;if(TYPES.indexOf(cf)>=0)$("filterType").value=cf;$("msgTo").innerHTML='<option value="">ALL</option>'+db.agents.map(function(a){return '<option value="'+esc(a.agent_id)+'">@'+esc(a.display_name)+" ("+esc(a.role)+")</option>";}).join("");$("msgAs").innerHTML='<option value="owner">Owner</option>'+db.agents.map(function(a){return '<option value="'+esc(a.agent_id)+'">Owner proxy '+esc(a.display_name)+" (NOT CONNECTED)</option>";}).join("");var chips=["@Architect","@Builder","@Researcher","@DarkStar","@Auditor"];db.agents.forEach(function(a){if(["chatgpt","grok","gemini","darkstar","auditor"].indexOf(a.agent_id)<0)chips.push("@"+a.display_name);});$("mentionChips").innerHTML=chips.map(function(c){return '<button type="button" class="chip" data-chip="'+esc(c)+'">'+esc(c)+"</button>";}).join("");}
  function renderTasks(){$("taskList").innerHTML=db.tasks.filter(function(t){return !t.parent_task_id;}).map(function(t){var last=t.last_activity_at?new Date(t.last_activity_at).toLocaleString():"-";var n=db.tasks.filter(function(s){return s.parent_task_id===t.task_id;}).length;return '<div class="card '+(t.task_id===db.selected?"active":"")+'" data-task="'+esc(t.task_id)+'"><div class="row"><span class="name">'+esc(t.task_id)+'</span><span class="status">'+sl(t.status)+"</span></div><div>"+esc(t.name)+'</div><div class="muted">'+membersOf(t.task_id).length+" Agents · "+esc(t.current_gate||"-")+" · "+n+' subtasks</div><div class="muted">'+esc(t.contract_id||"")+'</div><div class="muted">'+esc(t.progress_note||"")+'</div><div class="muted">Last: '+last+"</div></div>";}).join("")||'<div class="empty">No task until database connect.</div>';}
  function renderAgents(){$("agentList").innerHTML=db.agents.map(function(a){var cs=a.connection_status||"not_connected";return '<div class="card"><div class="row"><span class="name"><span class="dot" style="background:'+esc(a.color||"#8aa0b8")+'"></span>'+esc(a.display_name)+'</span><span class="muted">'+sl(a.status)+"</span></div><div class="muted">'+esc(a.role)+" · "+esc(a.capability)+'</div><div class="muted">Link: '+sl(cs)+'</div><div class="muted">Task: '+esc(a.current_task_id||"-")+'</div><div class="muted">Action: '+esc(a.current_action||"waiting")+"</div></div>";}).join("");}
  function renderPool(){var task=cur();if(!task){$("pool").innerHTML='<div class="empty">No task</div>';return;}var filter=$("filterType").value;var all=db.messages.filter(function(m){return m.task_id===task.task_id;});var msgs=all.filter(function(m){return !filter||m.message_type===filter;}).sort(function(a,b){return String(a.created_at).localeCompare(String(b.created_at));});$("poolMeta").textContent=task.task_id+" · "+msgs.length+" / "+all.length+" · no auto agent replies";if(!msgs.length){$("pool").innerHTML='<div class="empty">Pool is empty. No fake agent dialogue, commits, or test PASS.</div>';return;}$("pool").innerHTML=msgs.map(function(m){var from=m.sender_agent_id==="owner"?"Owner":((ag(m.sender_agent_id)||{}).display_name||m.sender_agent_id);var to=!m.receiver_agent_id?"ALL":((ag(m.receiver_agent_id)||{}).display_name||m.receiver_agent_id);var refs=db.code_refs.filter(function(r){return r.message_id===m.message_id;});var proxy=m.owner_proxy?'<div class="proxy">OWNER_PROXY / NOT CONNECTED</div>':"";return '<article class="msg"><div class="meta"><span class="tag '+esc(m.message_type)+'">'+esc(m.message_type)+"</span><b>"+esc(from)+"</b> -> "+esc(to)+" · "+new Date(m.created_at).toLocaleString()+"</div>"+proxy+"<div>"+hi(m.content)+"</div>"+refs.map(refHTML).join("")+"</article>";}).join("");}
  function renderRight(){var task=cur();if(!task)return;var g=db.gates[task.task_id]||db.gates[task.parent_task_id]||{};var root=task.parent_task_id||task.task_id;$("gates").innerHTML=GATES.map(function(k){var st=g[k[0]]||{state:"not_started",note:""};return '<div class="gate"><span>'+k[1]+"</span>"+gd(st.state)+"</div>"+(st.note?'<div class="muted">'+esc(st.note)+"</div>":"");}).join("");var subs=db.tasks.filter(function(t){return t.parent_task_id===root;});$("subs").innerHTML=subs.length?'<div class="tree">'+subs.map(function(s){return "- "+esc(s.task_id)+" "+esc(s.name)+" / "+esc(s.status)+" / "+(membersOf(s.task_id).join(", ")||"unassigned");}).join("<br>")+"</div>":'<div class="muted">No subtask</div>';var codes=db.code_refs.filter(function(r){return r.task_id===task.task_id||r.task_id===root;});$("codes").innerHTML=codes.length?codes.map(function(r){return '<div class="card">'+refHTML(r)+"</div>";}).join(""):'<div class="muted">No code ref</div>';var revs=db.reviews.filter(function(r){return r.task_id===task.task_id||r.task_id===root;});$("reviews").innerHTML=revs.length?revs.map(function(r){return '<div class="card"><div class="row"><span>'+esc(r.finding_id||r.review_id)+"</span><span>"+esc(r.status)+"</span></div><div>"+esc(r.findings||"")+"</div><div class="btn-row"><button class="btn" data-verdict="pass" data-review="'+esc(r.review_id)+'">PASS</button><button class="btn" data-verdict="need_fix" data-review="'+esc(r.review_id)+'">NEED FIX</button><button class="btn" data-verdict="reject" data-review="'+esc(r.review_id)+'">REJECT</button></div></div>';}).join(""):'<div class="muted">No review</div>';var tests=db.tests.filter(function(t){return t.task_id===task.task_id||t.task_id===root;});$("tests").innerHTML=tests.length?tests.map(function(t){return '<div class="card"><div class="row"><span>'+esc(t.suite)+'</span><span class="fail">'+esc(t.result)+"</span></div><div class=\"muted\">"+esc(t.detail||"")+"</div></div>";}).join(""):'<div class="muted">No test</div>';var learn=db.learning.filter(function(x){return x.task_id===task.task_id||x.task_id===root;});$("learn").innerHTML=learn.length?learn.map(function(x){return '<div class="card"><div>'+esc(x.problem||x.summary||"")+'</div><div class="muted">'+esc(x.verification_status)+(x.promoted?" promoted":" not promoted")+"</div></div>";}).join(""):'<div class="muted">No learning candidate. Not written to Dark Star.</div>';}
  function render(){setBadge();fill();renderTasks();renderAgents();renderPool();renderRight();}
  async function logAction(type,payload){var task=cur();if(!task)return;await rest("POST","agent_actions",{body:{task_id:task.task_id,actor_id:"owner",action_type:type,payload:payload||{}}});}
  async function postOwnerMessage(content,type,extra){var task=cur();extra=extra||{};await rest("POST","agent_messages",{body:{task_id:task.task_id,sender_agent_id:"owner",receiver_agent_id:extra.receiver_agent_id||null,message_type:type||"OWNER",content:content,reply_to:extra.reply_to||null,status:"posted",owner_proxy:false,action:extra.action||null,decision:extra.decision||null,evidence:extra.evidence||null,code_ref:extra.code_ref||null,review_ref:extra.review_ref||null,test_ref:extra.test_ref||null,gate_ref:extra.gate_ref||null,mentions:extra.mentions||[]}});}
  function on(id,ev,fn){var el=$(id);if(!el)return;el.addEventListener(ev,fn);}
  function bind(){
    on("taskList","click",function(e){var card=e.target.closest("[data-task]");if(!card)return;db.selected=card.getAttribute("data-task");render();});
    on("mentionChips","click",function(e){var chip=e.target.closest("[data-chip]");if(!chip)return;$("msgBody").value=($("msgBody").value?$("msgBody").value+" ":"")+chip.getAttribute("data-chip")+" ";});
    on("filterType","change",render);
    if($("btnConnect"))$("btnConnect").onclick=async function(){var url=($("sbUrl")&&$("sbUrl").value||"").trim().replace(/\/$/,"");var key=($("sbKey")&&$("sbKey").value||"").trim();if(key&&/service_role/i.test(key)){alert("service_role forbidden");return;}if(url&&key){conn={url:url,key:key,token:key,source:"form"};sessionStorage.setItem(CONN_KEY,JSON.stringify({url:url,key:key}));}else{conn=loadSavedConn()||detectSessionConn();}if(!conn){connState="not_connected";setBadge();setNote("NOT CONNECTED");return;}await connectAndLoad();};
    if($("btnReloadDb"))$("btnReloadDb").onclick=async function(){try{await requireConn();await refreshAll();render();}catch(err){setNote(err.message);}};
    if($("btnNewTask"))$("btnNewTask").onclick=async function(){try{await requireConn();var name=prompt("Task name");if(!name)return;var id=uid("task");await rest("POST","agent_tasks",{body:{task_id:id,parent_task_id:null,name:name,status:"draft",current_gate:"gate1",progress_note:"Owner created. No agent auto-run.",created_by:"owner"}});var i;for(i=0;i<GATES.length;i+=1){await rest("POST","agent_task_gates",{body:{task_id:id,gate_key:GATES[i][0],state:"not_started",note:""}});}db.selected=id;await logAction("create_task",{name:name});await refreshAll();render();}catch(err){alert(err.message);}};
    if($("btnAddAgent"))$("btnAddAgent").onclick=async function(){try{await requireConn();var id=($("newAgentId").value||"").trim().toLowerCase().replace(/[^a-z0-9_-]/g,"");var name=($("newAgentName").value||"").trim();if(!id||!name)return;await rest("POST","agent_registry",{body:{agent_id:id,display_name:name,role:($("newAgentRole").value||"").trim()||"agent",capability:($("newAgentCap").value||"").trim()||"",status:"waiting",connection_status:"not_connected",color:"#8aa0b8"}});await logAction("add_agent",{agent_id:id});await refreshAll();render();}catch(err){alert(err.message);}};
    if($("btnSend"))$("btnSend").onclick=async function(){try{await requireConn();var task=cur();if(!task)return;if(db.paused&&$("msgType").value!=="OWNER"){alert("paused");return;}var content=($("msgBody").value||"").trim();if(!content)return;var as=$("msgAs").value;var ms=mentions(content);var rows=await rest("POST","agent_messages",{body:{task_id:task.task_id,sender_agent_id:as,receiver_agent_id:$("msgTo").value||ms[0]||null,mentions:ms,message_type:$("msgType").value,content:content,reply_to:($("replyTo").value||"").trim()||null,status:"posted",owner_proxy:as!=="owner",code_ref:($("codePath").value||"").trim()||null}});var msg=Array.isArray(rows)?rows[0]:rows;var path=($("codePath").value||"").trim();var sha=($("codeSha").value||"").trim();if(path&&msg){await rest("POST","agent_code_refs",{body:{task_id:task.task_id,message_id:msg.message_id,file_path:path,commit_sha:sha||null,repo:"m9wmtcb782-arch/AIVAULT",created_by:as}});}if($("asLearning")&&$("asLearning").checked&&msg){await rest("POST","agent_learning_candidates",{body:{task_id:task.task_id,message_id:msg.message_id,source_agent_id:as,problem:(($("learnProblem")&&$("learnProblem").value)||content).slice(0,240),proposals:($("learnProposal")&&$("learnProposal").value)||null,chosen_solution:($("learnReason")&&$("learnReason").value)||null,reason:($("learnReason")&&$("learnReason").value)||null,summary:content.slice(0,240),verification_status:"candidate",promoted:false}});}if($("msgBody"))$("msgBody").value="";if($("codePath"))$("codePath").value="";if($("codeSha"))$("codeSha").value="";if($("asLearning"))$("asLearning").checked=false;await rest("PATCH","agent_tasks",{query:"?task_id=eq."+encodeURIComponent(task.task_id),body:{last_activity_at:now(),updated_at:now()}});await logAction("post_message",{message_id:msg&&msg.message_id});await refreshAll();render();}catch(err){alert(err.message);}};
    if($("btnReviewReq"))$("btnReviewReq").onclick=async function(){try{await requireConn();var task=cur();if(!task)return;var summary=($("msgBody").value||"").trim()||prompt("Review finding");if(!summary)return;var assigned=$("msgTo").value||"grok";var rows=await rest("POST","agent_reviews",{body:{task_id:task.task_id,finding_id:"F-"+String(db.reviews.length+1).padStart(3,"0"),requested_by:"owner",reviewer_agent_id:"chatgpt",target_agent_id:assigned,status:"requested",findings:summary,required_changes:""}});var review=Array.isArray(rows)?rows[0]:rows;await postOwnerMessage("REVIEW REQUEST "+(review&&review.finding_id)+": "+summary,"REVIEW",{receiver_agent_id:assigned,review_ref:review&&review.review_id,action:"REVIEW_REQUEST",mentions:[assigned]});await logAction("review_request",{});await refreshAll();render();}catch(err){alert(err.message);}};
    if($("reviews"))$("reviews").addEventListener("click",async function(e){var btn=e.target.closest("[data-review]");if(!btn)return;try{await requireConn();var id=btn.getAttribute("data-review");var verdict=btn.getAttribute("data-verdict");var r=db.reviews.find(function(x){return x.review_id===id;});if(!r)return;await rest("PATCH","agent_reviews",{query:"?review_id=eq."+encodeURIComponent(id),body:{status:verdict,resolved_at:(verdict==="pass"||verdict==="reject")?now():null}});var type=verdict==="pass"?"PASS":verdict==="reject"?"FAIL":"REVIEW";await postOwnerMessage("REVIEW "+(r.finding_id||id)+" = "+String(verdict).toUpperCase(),type,{receiver_agent_id:r.target_agent_id,review_ref:id,action:"REVIEW",decision:verdict});await refreshAll();render();}catch(err){alert(err.message);}});
    document.body.addEventListener("click",function(e){var ask=e.target.closest("[data-ask-review]");if(!ask)return;var ref=db.code_refs.find(function(r){return r.ref_id===ask.getAttribute("data-ask-review");});if(!ref)return;$("msgType").value="REVIEW";$("msgBody").value="@Architect review "+ref.file_path;$("codePath").value=ref.file_path;$("codeSha").value=ref.commit_sha||"";});
    if($("btnSubtask"))$("btnSubtask").onclick=async function(){try{await requireConn();var task=cur();if(!task)return;var parent=task.parent_task_id?db.tasks.find(function(t){return t.task_id===task.parent_task_id;}):task;var name=prompt("Subtask name");if(!name)return;var n=db.tasks.filter(function(t){return t.parent_task_id===parent.task_id;}).length+1;var id=parent.task_id+"-"+String.fromCharCode(64+n);var assignee=$("msgTo").value||"";await rest("POST","agent_tasks",{body:{task_id:id,parent_task_id:parent.task_id,name:name,status:"open",current_gate:parent.current_gate,progress_note:"Owner created. Not a live agent run.",contract_id:parent.contract_id||null,created_by:"owner"}});if(assignee)await rest("POST","agent_task_members",{body:{task_id:id,agent_id:assignee}});await logAction("create_subtask",{task_id:id});await refreshAll();render();}catch(err){alert(err.message);}};
    if($("btnTest"))$("btnTest").onclick=async function(){try{await requireConn();var task=cur();if(!task)return;var suite=prompt("Test suite","online_integration");if(!suite)return;var result=prompt("Result","NOT_RUN");if(!result)return;var detail=prompt("Detail","Not executed.")||"";var rows=await rest("POST","agent_test_results",{body:{task_id:task.task_id,suite:suite,result:result,detail:detail,created_by:"owner"}});var row=Array.isArray(rows)?rows[0]:rows;await postOwnerMessage("TEST "+suite+" = "+result+". "+detail,"TEST",{test_ref:row&&row.test_id,action:"TEST",evidence:detail});await refreshAll();render();}catch(err){alert(err.message);}};
    document.querySelectorAll("[data-own]").forEach(function(btn){btn.onclick=async function(){try{await requireConn();var task=cur();if(!task)return;var act=btn.getAttribute("data-own");if(!OWNER_ACTIONS[act])return;if($("msgAs")&&$("msgAs").value!=="owner"){alert("Owner-only");return;}var patch={updated_at:now(),last_activity_at:now()};if(act==="start"){db.paused=false;patch.status="working";patch.progress_note="Owner started workspace. WAITING FOR LIVE EXECUTION.";}if(act==="pause"){db.paused=true;patch.status="paused";}if(act==="rereview")patch.status="review";if(act==="reject")patch.status="blocked";if(act==="approve_prod"){if(!confirm("Record production intent? Will not deploy. Gate stays BLOCKED."))return;await rest("POST","agent_decisions",{body:{task_id:task.task_id,decision_type:"approve_production",actor_id:"owner",owner_required:true,approved:false,note:"PRODUCTION NOT DEPLOYED"}});}else if(act==="approve_change"||act==="approve_gate"||act==="reject"){if(act==="approve_gate"&&task.current_gate==="production"){alert("Production cannot pass via Approve Gate");return;}await rest("POST","agent_decisions",{body:{task_id:task.task_id,decision_type:act,actor_id:"owner",owner_required:true,approved:act!=="reject",note:"does not deploy"}});}if(act==="approve_gate"&&task.current_gate&&task.current_gate!=="production"){await rest("PATCH","agent_task_gates",{query:"?task_id=eq."+encodeURIComponent(task.task_id)+"&gate_key=eq."+encodeURIComponent(task.current_gate),body:{state:"waiting",note:"Owner intent only",updated_at:now()}});}await rest("PATCH","agent_tasks",{query:"?task_id=eq."+encodeURIComponent(task.task_id),body:patch});await postOwnerMessage("OWNER_ACTION "+act,"OWNER",{action:act,decision:act,gate_ref:task.current_gate||null});await logAction("owner_"+act,{});await refreshAll();render();}catch(err){alert(err.message);}};});
    if($("btnExport"))$("btnExport").onclick=function(){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="aivault-collab-v0.1.1.json";a.click();};
    if($("tabs"))$("tabs").addEventListener("click",function(e){var b=e.target.closest("[data-pane]");if(!b)return;var pane=b.getAttribute("data-pane");["left","mid","right"].forEach(function(p){if($("pane-"+p))$("pane-"+p).style.display=p===pane?"block":"none";});});
    if(window.matchMedia&&window.matchMedia("(max-width:980px)").matches){if($("pane-left"))$("pane-left").style.display="block";if($("pane-mid"))$("pane-mid").style.display="none";if($("pane-right"))$("pane-right").style.display="none";}
  }
  function boot(){bind();conn=loadSavedConn()||detectSessionConn();render();if(conn)connectAndLoad();else{connState="not_connected";setBadge();setNote("NOT CONNECTED. Database is the only store.");}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
